// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt967twNPNlqB5K0AHmM2Y4liTiBzmPdo',
    appId: '1:944670577029:web:0ca4f88c46d27eecb9f4ec',
    messagingSenderId: '944670577029',
    projectId: 'walltutorial-47abe',
    authDomain: 'walltutorial-47abe.firebaseapp.com',
    storageBucket: 'walltutorial-47abe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVWwNkz-Y7OnG50pmU4yl9_R3xsBX82kA',
    appId: '1:944670577029:android:56eba92452ada6a0b9f4ec',
    messagingSenderId: '944670577029',
    projectId: 'walltutorial-47abe',
    storageBucket: 'walltutorial-47abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHYw4V8dxOFlIV6co8hjhAD2dJgRm-FM',
    appId: '1:944670577029:ios:8b5a487b93f4eb0eb9f4ec',
    messagingSenderId: '944670577029',
    projectId: 'walltutorial-47abe',
    storageBucket: 'walltutorial-47abe.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYHYw4V8dxOFlIV6co8hjhAD2dJgRm-FM',
    appId: '1:944670577029:ios:8c9481d022d792b2b9f4ec',
    messagingSenderId: '944670577029',
    projectId: 'walltutorial-47abe',
    storageBucket: 'walltutorial-47abe.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
